#include "arraypos.c"

int main(){
    TabInt T;
    printf("masukkan jumlah elemen diikuti elemen-elemennya: \n");
    BacaIsi(&T);
    printf("array tersebut adalah: \n");
    TulisIsiTab(T);
    printf("\njumlah elemen efektif: %d\n", NbElmt(T));
    printf("jumlah elemen max: %d\n", MaxNbEl(T));
    printf("index elemen pertama: %d\n", GetFirstIdx(T));
    printf("index elemen terakhir: %d\n", GetLastIdx(T));
    printf("uji input indeks:\n");
    int index;
    scanf("%d", &index);
    printf("apakah index valid? %d\n", IsIdxValid(T, index));
    printf("apakah index efektif? %d\n", IsIdxEff(T, index));
    printf("apakah array kosong? %d\n", IsEmpty(T));
    printf("apakah array penuh? %d\n", IsFull(T));
    TabInt T2;
    printf("masukkan array kedua dengan jumlah efektif sama:\n");
    BacaIsi(&T2);
    printf("array kedua adalah: \n");
    TulisIsiTab(T2);
    printf("\ninput 1 untuk tambah, 0 untuk kurang: \n");
    boolean plus;
    scanf("%d", &plus);
    printf("operasi antara T dan T2 menjadi: \n");
    TabInt T4;
    T4 = PlusMinusTab(T, T2, plus);
    TulisIsiTab(T4);
    printf("\n");
    TulisIsiTab(T);
    printf("\n");
    TulisIsiTab(T2);
    printf("\napakah T = T2? %d\n", IsEQ(T, T2));
    printf("input bilangan yg akan dicari:\n");
    int x;
    scanf("%d", &x);
    printf("apakah bilangan tersebut ada pada array? %d\n", SearchB(T, x));
    printf("bilangan tersebut pertama kali muncul pada index %d\n", Search1(T, x));    
    printf("bilangan tersebut muncul sebanyak %d kali\n", CountX(T, x));    
    int max, min;
    MaxMin(T, &max, &min);
    printf("nilai max dan min array T adalah %d dan %d\n", max, min);
    printf("jumlah elemen pada array = %d\n", SumTab(T));
    printf("apakah seluruh elemen genap? %d\n", IsAllGenap(T));
    printf("input 1 untuk ascending, 0 untuk descending:\n");
    boolean asc;
    scanf("%d", &asc);
    Sort(&T, asc);
    TulisIsiTab(T);
    int y;
    printf("\ninput elemen y untuk ditambahkan ke elemen terakhir array:\n");
    scanf("%d", &y);
    AddAsLastEl(&T, y);
    printf("array menjadi:\n");
    TulisIsiTab(T);
    int z;
    DelLastEl(&T, &z);
    printf("\nelemen %d berhasil dihapus dari index terakhir, array menjadi:\n", z);
    TulisIsiTab(T);
    return 0;
}